### ISSUE TITLE
32-bit error

### ISSUE THREAD

**Issue by ThomasLengeling** [RSG/Carnivore#1]
Hello

I just starting to try the library on a windows 64bit and I'm getting the following error message, "Can't load IA 32-bit .dll on a AMD 64-bit platform"

Error--can't load native library.

Make sure you have installed winpcap (http://www.winpcap.org)
and that jpcap.dll is in the same folder as this application.

[org.rsg.carnivore.net.Devices] UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: C:\Users\thomas\Documents\Programacion\Processing\programas processing\libraries\carnivore\library\jpcap.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
[org.rsg.carnivore.net.Devices] Found network devices: {}
[org.rsg.carnivore.Core] starting PacketCacheThread
[org.rsg.carnivore.Core] addCarnivoreListener: org.rsg.carnivore.CarnivoreP5@2e1551b0
[org.rsg.carnivore.Preferences] loading preference file: .carnivore_preferences.txt
[org.rsg.carnivore.Preferences] saving prefs to disk: .carnivore_preferences.txt
[CarnivoreP5] dispose()

**Comment by RSG** [comment]
(apologies for the delay) -- the short answer is that Carnivore is really not supported any more on Windows. i simply don't have access to enough Win machines to be able to test it properly. hopefully in the future i'll be able to find a simple implementation for this. but for now you're out of luck, sorry.

**Comment by paulsmithkc** [comment]
This issue still isn't fixed...

**Comment by filobotica** [comment]
winpcap not work for windows 10 :(
Anyone tried nmap?

**Comment by paulsmithkc** [comment]
nmap doesn't have very good dataviz. And you can't hook it up to a smart mirror. 😟
